# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.buttercup.example.com:
  peer1.buttercup.example.com:
  peer0.popstar.example.com:
  peer1.popstar.example.com:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.buttercup.example.com:
    container_name: peer0.buttercup.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.buttercup.example.com
    networks:
      - byfn

  peer1.buttercup.example.com:
    container_name: peer1.buttercup.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.buttercup.example.com
    networks:
      - byfn

  peer0.popstar.example.com:
    container_name: peer0.popstar.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.popstar.example.com
    networks:
      - byfn

  peer1.popstar.example.com:
    container_name: peer1.popstar.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.popstar.example.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.buttercup.example.com:7051
      - CORE_PEER_LOCALMSPID=ButtercupMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/buttercup.example.com/peers/peer0.buttercup.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/buttercup.example.com/peers/peer0.buttercup.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/buttercup.example.com/peers/peer0.buttercup.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/buttercup.example.com/users/Admin@buttercup.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./trace-fruits-cc:/opt/gopath/src/github.com/hyperledger/fabric/splunk/chaincode/go
        - ./trace-fruits-cc/trace:/opt/gopath/src/github.com/trace-fruits-cc/trace
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.buttercup.example.com
      - peer1.buttercup.example.com
      - peer0.popstar.example.com
      - peer1.popstar.example.com
    networks:
      - byfn
