# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.buttercup.example.com:
    container_name: peer0.buttercup.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.buttercup.example.com
      - CORE_PEER_ADDRESS=peer0.buttercup.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.buttercup.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buttercup.example.com:7051
      - CORE_PEER_LOCALMSPID=ButtercupMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto/peerOrganizations/buttercup.example.com/peers/peer0.buttercup.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto/peerOrganizations/buttercup.example.com/peers/peer0.buttercup.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.buttercup.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.buttercup.example.com:
    container_name: peer1.buttercup.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.buttercup.example.com
      - CORE_PEER_ADDRESS=peer1.buttercup.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buttercup.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buttercup.example.com:7051
      - CORE_PEER_LOCALMSPID=ButtercupMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto/peerOrganizations/buttercup.example.com/peers/peer1.buttercup.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto/peerOrganizations/buttercup.example.com/peers/peer1.buttercup.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.buttercup.example.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.popstar.example.com:
    container_name: peer0.popstar.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.popstar.example.com
      - CORE_PEER_ADDRESS=peer0.popstar.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.popstar.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.popstar.example.com:7051
      - CORE_PEER_LOCALMSPID=PopstarMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto/peerOrganizations/popstar.example.com/peers/peer0.popstar.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto/peerOrganizations/popstar.example.com/peers/peer0.popstar.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.popstar.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.popstar.example.com:
    container_name: peer1.popstar.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.popstar.example.com
      - CORE_PEER_ADDRESS=peer1.popstar.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.popstar.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.popstar.example.com:7051
      - CORE_PEER_LOCALMSPID=PopstarMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto/peerOrganizations/popstar.example.com/peers/peer1.popstar.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto/peerOrganizations/popstar.example.com/peers/peer1.popstar.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.popstar.example.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
